version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qgp0SCY0xtPgMcdB9anaibuqFM0Y1JsHKhFH7BTiqJAS1Y54aL
      - POSTGRES_DB=forum_site
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local