version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=duckduckcodes
      - POSTGRES_PASSWORD=1QJRkiyBvwWJ5cH6M7WMLb0oR485xUz6Ta56aen3ROqOAt8pfd
      - POSTGRES_DB=forum
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

volumes:
  db:
    driver: local
